### PR TITLE
FIX: Filter bypass leading to XSS

### PR DESCRIPTION
**Pull request by v1dhun**
### ❓ Technical description

Filter bypass leading to XSS

### 🐛 Proof of Vulnerability (PoV)

https://github.com/trentm/python-markdown2/issues/348

### 🔥 Proof of Fix (PoF)

Screenshot_2020-05-03 AL XSS Catcher - Regex Tester Debugger

### CODE REVIEW

**Comment by v1dhun** [comment]
Hi @huntr-helper,  any update on this?

**Comment by JamieSlome** [comment]
Hi @V1dhun - your pull request will be reviewed at the end of the week when the team does bounty reviews! 🍰 

Although, it does seem that this issue may have already been addressed externally: https://github.com/trentm/python-markdown2/issues/348 🎉

**Comment by JamieSlome** [comment]
After reviewing the issue (https://github.com/trentm/python-markdown2/issues/348) it looks like a fix has already been accepted (https://github.com/trentm/python-markdown2/pull/353).

Thank you! 🍰

**Review by JamieSlome — COMMENTED** [review]
Very nice usage of the template :)

In this instance, a fix was already provided to the root repository: https://github.com/trentm/python-markdown2/pull/353

Thanks! 🍰

**Comment by huntr-helper** [comment]
Sorry @V1dhun, we enjoyed reviewing your fix but it has not been selected this time. If this bounty has not been closed, please feel free to try again with a new pull request! We appreciate your effort and look forward to reviewing more of your fixes in the future! :hammer: :sunglasses:

**Pull request closed without merging**
